### ISSUE TITLE
[FEATURE] TYPO3 8.7 compatible

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/scheduler_timeline#40]
* Add composer.json
* Update .travis.yml
* Upgrade for TYPO3 8.7 Compatibility

**Comment by tomasnorre** [comment]
I've experienced problems with the Scheduler Timeline rendering.. Will fix this as part of this update, as i've only seen it broken in TYPO3 8.7

**Update** 
The problem is that the viewhelpers have changed in TYPO3 8, We need to write from render() to renderStatic. 

![screen shot 2017-12-15 at 19 39 00](https://user-images.githubusercontent.com/1212481/34055644-7b61616c-e1d0-11e7-91a3-a5187afbc5c4.png)
![screen shot 2017-12-15 at 19 44 17](https://user-images.githubusercontent.com/1212481/34055645-7b7c4482-e1d0-11e7-8250-2a909d1c5b6f.png)

**Comment by wojtablo** [comment]
hey, when do you plan to add support for TYPO3 8.x?

**Comment by tomasnorre** [comment]
Hi @wojtablo 

There is already a branch for it. But there is problems with one of the xclasses as I recall it. That i would need to look into. 

If you like, you can have a look at the Branch, https://github.com/AOEpeople/scheduler_timeline/tree/issue/40, it's work in progress.

**Comment by tomasnorre** [comment]
Resolves with #47
